spring:
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: false
    #        generate-ddl: true
    hibernate:
      ddl-auto: none
  mvc:
    hiddenmethod:
      filter:
        enabled: true